<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
            ['name' => 'Hryvnia', 'iso_code' => 'UAH', 'numeric_code' => 980, 'minor_unit' => 2],
            ['name' => 'Afghani', 'iso_code' => 'AFN', 'numeric_code' => 971, 'minor_unit' => 2],
            ['name' => 'Euro', 'iso_code' => 'EUR', 'numeric_code' => 978, 'minor_unit' => 2],
            ['name' => 'Lek', 'iso_code' => 'ALL', 'numeric_code' => 8, 'minor_unit' => 2],
            ['name' => 'Algerian Dinar', 'iso_code' => 'DZD', 'numeric_code' => 12, 'minor_unit' => 2],
            ['name' => 'US Dollar', 'iso_code' => 'USD', 'numeric_code' => 840, 'minor_unit' => 2],
            ['name' => 'Kwanza', 'iso_code' => 'AOA', 'numeric_code' => 973, 'minor_unit' => 2],
            ['name' => 'East Caribbean Dollar', 'iso_code' => 'XCD', 'numeric_code' => 951, 'minor_unit' => 2],
            ['name' => 'Argentine Peso', 'iso_code' => 'ARS', 'numeric_code' => 32, 'minor_unit' => 2],
            ['name' => 'Armenian Dram', 'iso_code' => 'AMD', 'numeric_code' => 51, 'minor_unit' => 2],
            ['name' => 'Aruban Florin', 'iso_code' => 'AWG', 'numeric_code' => 533, 'minor_unit' => 2],
            ['name' => 'Australian Dollar', 'iso_code' => 'AUD', 'numeric_code' => 36, 'minor_unit' => 2],
            ['name' => 'Azerbaijan Manat', 'iso_code' => 'AZN', 'numeric_code' => 944, 'minor_unit' => 2],
            ['name' => 'Bahamian Dollar', 'iso_code' => 'BSD', 'numeric_code' => 44, 'minor_unit' => 2],
            ['name' => 'Bahraini Dinar', 'iso_code' => 'BHD', 'numeric_code' => 48, 'minor_unit' => 3],
            ['name' => 'Taka', 'iso_code' => 'BDT', 'numeric_code' => 50, 'minor_unit' => 2],
            ['name' => 'Barbados Dollar', 'iso_code' => 'BBD', 'numeric_code' => 52, 'minor_unit' => 2],
            ['name' => 'Belarusian Ruble', 'iso_code' => 'BYN', 'numeric_code' => 933, 'minor_unit' => 2],
            ['name' => 'Belize Dollar', 'iso_code' => 'BZD', 'numeric_code' => 84, 'minor_unit' => 2],
            ['name' => 'CFA Franc BCEAO', 'iso_code' => 'XOF', 'numeric_code' => 952, 'minor_unit' => 0],
            ['name' => 'Bermudian Dollar', 'iso_code' => 'BMD', 'numeric_code' => 60, 'minor_unit' => 2],
            ['name' => 'Indian Rupee', 'iso_code' => 'INR', 'numeric_code' => 356, 'minor_unit' => 2],
            ['name' => 'Ngultrum', 'iso_code' => 'BTN', 'numeric_code' => 64, 'minor_unit' => 2],
            ['name' => 'Boliviano', 'iso_code' => 'BOB', 'numeric_code' => 68, 'minor_unit' => 2],
            ['name' => 'Mvdol (Funds code)', 'iso_code' => 'BOV', 'numeric_code' => 984, 'minor_unit' => 2],
            ['name' => 'Convertible Mark', 'iso_code' => 'BAM', 'numeric_code' => 977, 'minor_unit' => 2],
            ['name' => 'Pula', 'iso_code' => 'BWP', 'numeric_code' => 72, 'minor_unit' => 2],
            ['name' => 'Norwegian Krone', 'iso_code' => 'NOK', 'numeric_code' => 578, 'minor_unit' => 2],
            ['name' => 'Brazilian Real', 'iso_code' => 'BRL', 'numeric_code' => 986, 'minor_unit' => 2],
            ['name' => 'Brunei Dollar', 'iso_code' => 'BND', 'numeric_code' => 96, 'minor_unit' => 2],
            ['name' => 'Bulgarian Lev', 'iso_code' => 'BGN', 'numeric_code' => 975, 'minor_unit' => 2],
            ['name' => 'Burundi Franc', 'iso_code' => 'BIF', 'numeric_code' => 108, 'minor_unit' => 0],
            ['name' => 'Cabo Verde Escudo', 'iso_code' => 'CVE', 'numeric_code' => 132, 'minor_unit' => 2],
            ['name' => 'Riel', 'iso_code' => 'KHR', 'numeric_code' => 116, 'minor_unit' => 2],
            ['name' => 'CFA Franc BEAC', 'iso_code' => 'XAF', 'numeric_code' => 950, 'minor_unit' => 0],
            ['name' => 'Canadian Dollar', 'iso_code' => 'CAD', 'numeric_code' => 124, 'minor_unit' => 2],
            ['name' => 'Cayman Islands Dollar', 'iso_code' => 'KYD', 'numeric_code' => 136, 'minor_unit' => 2],
            ['name' => 'Chilean Peso', 'iso_code' => 'CLP', 'numeric_code' => 152, 'minor_unit' => 0],
            ['name' => 'Unidad de Fomento (Funds code)', 'iso_code' => 'CLF', 'numeric_code' => 990, 'minor_unit' => 4],
            ['name' => 'Yuan Renminbi', 'iso_code' => 'CNY', 'numeric_code' => 156, 'minor_unit' => 2],
            ['name' => 'Colombian Peso', 'iso_code' => 'COP', 'numeric_code' => 170, 'minor_unit' => 2],
            ['name' => 'Unidad de Valor Real (Funds code)', 'iso_code' => 'COU', 'numeric_code' => 970, 'minor_unit' => 2],
            ['name' => 'Comorian Franc', 'iso_code' => 'KMF', 'numeric_code' => 174, 'minor_unit' => 0],
            ['name' => 'Congolese Franc', 'iso_code' => 'CDF', 'numeric_code' => 976, 'minor_unit' => 2],
            ['name' => 'New Zealand Dollar', 'iso_code' => 'NZD', 'numeric_code' => 554, 'minor_unit' => 2],
            ['name' => 'Costa Rican Colon', 'iso_code' => 'CRC', 'numeric_code' => 188, 'minor_unit' => 2],
            ['name' => 'Cuban Peso', 'iso_code' => 'CUP', 'numeric_code' => 192, 'minor_unit' => 2],
            ['name' => 'Peso Convertible', 'iso_code' => 'CUC', 'numeric_code' => 931, 'minor_unit' => 2],
            ['name' => 'Netherlands Antillean Guilder', 'iso_code' => 'ANG', 'numeric_code' => 532, 'minor_unit' => 2],
            ['name' => 'Czech Koruna', 'iso_code' => 'CZK', 'numeric_code' => 203, 'minor_unit' => 2],
            ['name' => 'Danish Krone', 'iso_code' => 'DKK', 'numeric_code' => 208, 'minor_unit' => 2],
            ['name' => 'Djibouti Franc', 'iso_code' => 'DJF', 'numeric_code' => 262, 'minor_unit' => 0],
            ['name' => 'Dominican Peso', 'iso_code' => 'DOP', 'numeric_code' => 214, 'minor_unit' => 2],
            ['name' => 'Egyptian Pound', 'iso_code' => 'EGP', 'numeric_code' => 818, 'minor_unit' => 2],
            ['name' => 'El Salvador Colon', 'iso_code' => 'SVC', 'numeric_code' => 222, 'minor_unit' => 2],
            ['name' => 'Nakfa', 'iso_code' => 'ERN', 'numeric_code' => 232, 'minor_unit' => 2],
            ['name' => 'Ethiopian Birr', 'iso_code' => 'ETB', 'numeric_code' => 230, 'minor_unit' => 2],
            ['name' => 'Falkland Islands Pound', 'iso_code' => 'FKP', 'numeric_code' => 238, 'minor_unit' => 2],
            ['name' => 'Fiji Dollar', 'iso_code' => 'FJD', 'numeric_code' => 242, 'minor_unit' => 2],
            ['name' => 'CFP Franc', 'iso_code' => 'XPF', 'numeric_code' => 953, 'minor_unit' => 0],
            ['name' => 'Dalasi', 'iso_code' => 'GMD', 'numeric_code' => 270, 'minor_unit' => 2],
            ['name' => 'Lari', 'iso_code' => 'GEL', 'numeric_code' => 981, 'minor_unit' => 2],
            ['name' => 'Ghana Cedi', 'iso_code' => 'GHS', 'numeric_code' => 936, 'minor_unit' => 2],
            ['name' => 'Gibraltar Pound', 'iso_code' => 'GIP', 'numeric_code' => 292, 'minor_unit' => 2],
            ['name' => 'Guinean Franc', 'iso_code' => 'GNF', 'numeric_code' => 324, 'minor_unit' => 0],
            ['name' => 'Guyana Dollar', 'iso_code' => 'GYD', 'numeric_code' => 328, 'minor_unit' => 2],
            ['name' => 'Gourde', 'iso_code' => 'HTG', 'numeric_code' => 332, 'minor_unit' => 2],
            ['name' => 'Lempira', 'iso_code' => 'HNL', 'numeric_code' => 340, 'minor_unit' => 2],
            ['name' => 'Hong Kong Dollar', 'iso_code' => 'HKD', 'numeric_code' => 344, 'minor_unit' => 2],
            ['name' => 'Forint', 'iso_code' => 'HUF', 'numeric_code' => 348, 'minor_unit' => 2],
            ['name' => 'Iceland Krona', 'iso_code' => 'ISK', 'numeric_code' => 352, 'minor_unit' => 0],
            ['name' => 'Rupiah', 'iso_code' => 'IDR', 'numeric_code' => 360, 'minor_unit' => 2],
            ['name' => 'SDR (Special Drawing Right)', 'iso_code' => 'XDR', 'numeric_code' => 960, 'minor_unit' => null],
            ['name' => 'Iranian Rial', 'iso_code' => 'IRR', 'numeric_code' => 364, 'minor_unit' => 2],
            ['name' => 'Iraqi Dinar', 'iso_code' => 'IQD', 'numeric_code' => 368, 'minor_unit' => 3],
            ['name' => 'New Israeli Sheqel', 'iso_code' => 'ILS', 'numeric_code' => 376, 'minor_unit' => 2],
            ['name' => 'Jamaican Dollar', 'iso_code' => 'JMD', 'numeric_code' => 388, 'minor_unit' => 2],
            ['name' => 'Yen', 'iso_code' => 'JPY', 'numeric_code' => 392, 'minor_unit' => 0],
            ['name' => 'Jordanian Dinar', 'iso_code' => 'JOD', 'numeric_code' => 400, 'minor_unit' => 3],
            ['name' => 'Tenge', 'iso_code' => 'KZT', 'numeric_code' => 398, 'minor_unit' => 2],
            ['name' => 'Kenyan Shilling', 'iso_code' => 'KES', 'numeric_code' => 404, 'minor_unit' => 2],
            ['name' => 'Som', 'iso_code' => 'KGS', 'numeric_code' => 417, 'minor_unit' => 2],
            ['name' => 'Won', 'iso_code' => 'KRW', 'numeric_code' => 410, 'minor_unit' => 0],
            ['name' => 'Kuwaiti Dinar', 'iso_code' => 'KWD', 'numeric_code' => 414, 'minor_unit' => 3],
            ['name' => 'Lao Kip', 'iso_code' => 'LAK', 'numeric_code' => 418, 'minor_unit' => 2],
            ['name' => 'Lebanese Pound', 'iso_code' => 'LBP', 'numeric_code' => 422, 'minor_unit' => 2],
            ['name' => 'Liberian Dollar', 'iso_code' => 'LRD', 'numeric_code' => 430, 'minor_unit' => 2],
            ['name' => 'Loti', 'iso_code' => 'LSL', 'numeric_code' => 426, 'minor_unit' => 2],
            ['name' => 'Libyan Dinar', 'iso_code' => 'LYD', 'numeric_code' => 434, 'minor_unit' => 3],
            ['name' => 'Swiss Franc', 'iso_code' => 'CHF', 'numeric_code' => 756, 'minor_unit' => 2],
            ['name' => 'Ariary', 'iso_code' => 'MGA', 'numeric_code' => 969, 'minor_unit' => 2],
            ['name' => 'Denar', 'iso_code' => 'MKD', 'numeric_code' => 807, 'minor_unit' => 2],
            ['name' => 'Kwacha', 'iso_code' => 'MWK', 'numeric_code' => 454, 'minor_unit' => 2],
            ['name' => 'Ringgit', 'iso_code' => 'MYR', 'numeric_code' => 458, 'minor_unit' => 2],
            ['name' => 'Rufiyaa', 'iso_code' => 'MVR', 'numeric_code' => 462, 'minor_unit' => 2],
            ['name' => 'Ouguiya', 'iso_code' => 'MRU', 'numeric_code' => 929, 'minor_unit' => 2],
            ['name' => 'Mauritius Rupee', 'iso_code' => 'MUR', 'numeric_code' => 480, 'minor_unit' => 2],
            ['name' => 'Mexican Peso', 'iso_code' => 'MXN', 'numeric_code' => 484, 'minor_unit' => 2],
            ['name' => 'Moldovan Leu', 'iso_code' => 'MDL', 'numeric_code' => 498, 'minor_unit' => 2],
            ['name' => 'Turkish Lira', 'iso_code' => 'TRY', 'numeric_code' => 949, 'minor_unit' => 2],
            ['name' => 'Zloty', 'iso_code' => 'PLN', 'numeric_code' => 985, 'minor_unit' => 2],
            ['name' => 'Pound sterling', 'iso_code' => 'GBP', 'numeric_code' => 826, 'minor_unit' => 2],
            ['name' => 'UAE dirham', 'iso_code' => 'AED', 'numeric_code' => 784, 'minor_unit' => 2],
            ['name' => 'Croatian kuna', 'iso_code' => 'HRK', 'numeric_code' => 191, 'minor_unit' => 2],
            ['name' => 'Sri Lankan rupee', 'iso_code' => 'LKR', 'numeric_code' => 144, 'minor_unit' => 2],
            ['name' => 'Moroccan dirham', 'iso_code' => 'MAD', 'numeric_code' => 504, 'minor_unit' => 2],
            ['name' => 'Mongolian tögrög', 'iso_code' => 'MNT', 'numeric_code' => 496, 'minor_unit' => 2],
            ['name' => 'Mozambican metical', 'iso_code' => 'MZN', 'numeric_code' => 943, 'minor_unit' => 2],
            ['name' => 'Namibian dollar', 'iso_code' => 'NAD', 'numeric_code' => 516, 'minor_unit' => 2],
            ['name' => 'Nigerian naira', 'iso_code' => 'NGN', 'numeric_code' => 566, 'minor_unit' => 2],
            ['name' => 'Nicaraguan córdoba', 'iso_code' => 'NIO', 'numeric_code' => 558, 'minor_unit' => 2],
            ['name' => 'Nepalese rupee', 'iso_code' => 'NPR', 'numeric_code' => 524, 'minor_unit' => 2],
            ['name' => 'Omani rial', 'iso_code' => 'OMR', 'numeric_code' => 512, 'minor_unit' => 3],
            ['name' => 'Peruvian sol', 'iso_code' => 'PEN', 'numeric_code' => 604, 'minor_unit' => 2],
            ['name' => 'Philippine peso', 'iso_code' => 'PHP', 'numeric_code' => 608, 'minor_unit' => 2],
            ['name' => 'Pakistani rupee', 'iso_code' => 'PKR', 'numeric_code' => 586, 'minor_unit' => 2],
            ['name' => 'Paraguayan guaraní', 'iso_code' => 'PYG', 'numeric_code' => 600, 'minor_unit' => 0],
            ['name' => 'Qatari riyal', 'iso_code' => 'QAR', 'numeric_code' => 634, 'minor_unit' => 2],
            ['name' => 'Romanian leu', 'iso_code' => 'RON', 'numeric_code' => 946, 'minor_unit' => 2],
            ['name' => 'Serbian dinar', 'iso_code' => 'RSD', 'numeric_code' => 941, 'minor_unit' => 2],
            ['name' => 'Saudi riyal', 'iso_code' => 'SAR', 'numeric_code' => 682, 'minor_unit' => 2],
            ['name' => 'Seychellois rupee', 'iso_code' => 'SCR', 'numeric_code' => 690, 'minor_unit' => 2],
            ['name' => 'Sudanese pound', 'iso_code' => 'SDG', 'numeric_code' => 938, 'minor_unit' => 2],
            ['name' => 'Swedish krona', 'iso_code' => 'SEK', 'numeric_code' => 752, 'minor_unit' => 2],
            ['name' => 'Singapore dollar', 'iso_code' => 'SGD', 'numeric_code' => 702, 'minor_unit' => 2],
            ['name' => 'Sierra Leonean leone', 'iso_code' => 'SLL', 'numeric_code' => 694, 'minor_unit' => 0],
            ['name' => 'Somali shilling', 'iso_code' => 'SOS', 'numeric_code' => 706, 'minor_unit' => 2],
            ['name' => 'Surinamese dollar', 'iso_code' => 'SRD', 'numeric_code' => 968, 'minor_unit' => 2],
            ['name' => 'Swazi lilangeni', 'iso_code' => 'SZL', 'numeric_code' => 748, 'minor_unit' => 2],
            ['name' => 'Thai baht', 'iso_code' => 'THB', 'numeric_code' => 764, 'minor_unit' => 2],
            ['name' => 'Tajikistani somoni', 'iso_code' => 'TJS', 'numeric_code' => 972, 'minor_unit' => 2],
            ['name' => 'Tunisian dinar', 'iso_code' => 'TND', 'numeric_code' => 788, 'minor_unit' => 3],
            ['name' => 'New Taiwan dollar', 'iso_code' => 'TWD', 'numeric_code' => 901, 'minor_unit' => 2],
            ['name' => 'Tanzanian shilling', 'iso_code' => 'TZS', 'numeric_code' => 834, 'minor_unit' => 2],
            ['name' => 'Ugandan shilling', 'iso_code' => 'UGX', 'numeric_code' => 800, 'minor_unit' => 0],
            ['name' => 'Uruguayan peso', 'iso_code' => 'UYU', 'numeric_code' => 858, 'minor_unit' => 2],
            ['name' => 'Uzbekistani soʻm', 'iso_code' => 'UZS', 'numeric_code' => 860, 'minor_unit' => 2],
            ['name' => 'Vietnamese đồng', 'iso_code' => 'VND', 'numeric_code' => 704, 'minor_unit' => 0],
            ['name' => 'Yemeni rial', 'iso_code' => 'YER', 'numeric_code' => 886, 'minor_unit' => 2],
            ['name' => 'South African rand', 'iso_code' => 'ZAR', 'numeric_code' => 710, 'minor_unit' => 2],
        ];
        foreach ($currencies as $currency) {
            Currency::updateOrCreate($currency);
        }
    }
}
