backend:
  - changed-files:
      - any-glob-to-any-file:
          - app/**

database:
  - changed-files:
      - any-glob-to-any-file:
          - database/**

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - resourses/**

tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**
